/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frontend;

import Backend.Student;
import Controller.Controller;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import laab5.Laab5;

/**
 *
 * @author mo
 */
public class SearchStudent extends javax.swing.JPanel {

    /**
     * Creates new form SearchStudent
     */
    public SearchStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        optiongender = new javax.swing.JComboBox<>();
        Department = new javax.swing.JLabel();
        textstudentAge = new javax.swing.JTextField();
        textdepartment = new javax.swing.JTextField();
        StudentName = new javax.swing.JLabel();
        textgpa = new javax.swing.JTextField();
        textstudentname = new javax.swing.JTextField();
        Gpa = new javax.swing.JLabel();
        Age = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        SaveChanges = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        Search.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Search.setForeground(new java.awt.Color(153, 153, 255));
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Age", "Gender", "Department", "Gpa"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        optiongender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gender Selection", "Male", "Female" }));
        optiongender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optiongenderActionPerformed(evt);
            }
        });

        Department.setBackground(new java.awt.Color(255, 255, 255));
        Department.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Department.setForeground(new java.awt.Color(153, 153, 255));
        Department.setText("Department:");

        textstudentAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textstudentAgeActionPerformed(evt);
            }
        });

        textdepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textdepartmentActionPerformed(evt);
            }
        });

        StudentName.setBackground(new java.awt.Color(255, 255, 255));
        StudentName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        StudentName.setForeground(new java.awt.Color(153, 153, 255));
        StudentName.setText("Student Name:");

        textgpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textgpaActionPerformed(evt);
            }
        });

        textstudentname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textstudentnameActionPerformed(evt);
            }
        });

        Gpa.setBackground(new java.awt.Color(255, 255, 255));
        Gpa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Gpa.setForeground(new java.awt.Color(153, 153, 255));
        Gpa.setText("GPA:");

        Age.setBackground(new java.awt.Color(255, 255, 255));
        Age.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Age.setForeground(new java.awt.Color(153, 153, 255));
        Age.setText("Age:");

        Gender.setBackground(new java.awt.Color(255, 255, 255));
        Gender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Gender.setForeground(new java.awt.Color(153, 153, 255));
        Gender.setText("Gender:");

        SaveChanges.setBackground(new java.awt.Color(204, 204, 204));
        SaveChanges.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SaveChanges.setForeground(new java.awt.Color(153, 153, 255));
        SaveChanges.setText("Save Changes");
        SaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveChangesActionPerformed(evt);
            }
        });

        Back.setBackground(new java.awt.Color(204, 204, 204));
        Back.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Back.setForeground(new java.awt.Color(153, 153, 255));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)
                                .addComponent(Search))
                            .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Department, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(StudentName)
                                    .addGap(76, 76, 76)
                                    .addComponent(textstudentname, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(optiongender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textstudentAge, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textdepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textgpa, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Gpa, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addComponent(SaveChanges, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Search))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StudentName))
                    .addComponent(textstudentname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Age)
                    .addComponent(textstudentAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gender)
                    .addComponent(optiongender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Department)
                    .addComponent(textdepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gpa)
                    .addComponent(textgpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveChanges)
                    .addComponent(Back))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void optiongenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optiongenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optiongenderActionPerformed

    private void textstudentAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textstudentAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textstudentAgeActionPerformed

    private void textdepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textdepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textdepartmentActionPerformed

    private void textgpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textgpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textgpaActionPerformed

    private void textstudentnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textstudentnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textstudentnameActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HomePage().setVisible(true);

    }//GEN-LAST:event_BackActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String search = jTextField1.getText().trim();
            
            if (search.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Pleasr enter name or ID ");
                return;
            }
            
            Controller control = Laab5.getController();
            List<Student> studentsList = control.getAllStudents();
            
            DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
            table.setRowCount(0);
            
            boolean flag = false;
            
            for (Student s : studentsList) {
                if (String.valueOf(s.getID()).equalsIgnoreCase(search) || s.getName().equalsIgnoreCase(search)) {
                    
                    table.addRow(new Object[]{s.getID(), s.getName(), s.getAge(), s.getGender(), s.getDepartment(), s.getGPA()
                    });
                    textstudentname.setText(s.getName());
                    textstudentAge.setText(String.valueOf(s.getAge()));
                    optiongender.setSelectedItem(s.getGender());
                    textdepartment.setText(s.getDepartment());
                    textgpa.setText(String.valueOf(s.getGPA()));
                    
                    flag = true;
                    break;
                }
                
            }
            
            if (!flag) {
                JOptionPane.showMessageDialog(this, "No student found with that ID or Name.");
            }
        } catch (IOException ex) {
            Logger.getLogger(SearchStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SearchActionPerformed

    private void SaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveChangesActionPerformed
        // TODO add your handling code here:
        
         try {
            String name = textstudentname.getText().trim();
            String age = textstudentAge.getText().trim();
            String gender = optiongender.getSelectedItem().toString();
            String department = textdepartment.getText().trim();
            String gpa = textgpa.getText().trim();

            if (name.isEmpty() || age.isEmpty() || gender.equals("Gender Selection") || department.isEmpty() || gpa.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill all fields.");
                return;
            }

            int ageValue = Integer.parseInt(age);
            double gpaValue = Double.parseDouble(gpa);

            // GPA validation
            if (gpaValue < 0.0 || gpaValue > 4.0) {
                JOptionPane.showMessageDialog(this, "GPA must be between 0.0 and 4.0");
                return;
            }

            int id = Integer.parseInt(jTable1.getValueAt(0, 0).toString());
            Controller control = Laab5.getController();
            control.updateStudent(id, name, ageValue, gender, department, gpaValue);

            JOptionPane.showMessageDialog(this, "Successfully updated.");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numbers for Age and GPA.");
        } catch (IOException ex) {
            Logger.getLogger(SearchStudent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_SaveChangesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age;
    private javax.swing.JButton Back;
    private javax.swing.JLabel Department;
    private javax.swing.JLabel Gender;
    private javax.swing.JLabel Gpa;
    private javax.swing.JButton SaveChanges;
    private javax.swing.JButton Search;
    private javax.swing.JLabel StudentName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> optiongender;
    private javax.swing.JTextField textdepartment;
    private javax.swing.JTextField textgpa;
    private javax.swing.JTextField textstudentAge;
    private javax.swing.JTextField textstudentname;
    // End of variables declaration//GEN-END:variables
}
